import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import Build from '../components/Build'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Item from '../components/Item'
import Main from '../components/Main'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 
       <Header/>

      <Banner/> 

     <Item/> 

     <Main/>

     <Footer/>
    </div>
  )
}
